"""
market_export_service.py — Export market analysis as PDF, DOCX, or plain text.
Generates professional reports from structured MarketAnalysis JSON data.
"""
import io
from datetime import datetime, timezone

from app.models.market_analysis import MarketAnalysis
from app.services.export_service import _sanitize_latin1


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _fmt_usd(n: int | float | None) -> str:
    """Format a USD value with appropriate suffix."""
    if n is None:
        return "$0"
    if n >= 1_000_000_000:
        return f"${n / 1_000_000_000:.1f}B"
    if n >= 1_000_000:
        return f"${n / 1_000_000:.1f}M"
    if n >= 1_000:
        return f"${n / 1_000:.0f}K"
    return f"${n:,.0f}"


def _fmt_number(n: int | float | None) -> str:
    """Format a number with appropriate suffix."""
    if n is None:
        return "0"
    if n >= 1_000_000:
        return f"{n / 1_000_000:.1f}M"
    if n >= 1_000:
        return f"{n / 1_000:.1f}K"
    return f"{n:,}"


def _safe(val, default="N/A"):
    """Return val if truthy, else default."""
    return val if val else default


# ---------------------------------------------------------------------------
# PDF generation
# ---------------------------------------------------------------------------

def generate_pdf(analysis: MarketAnalysis, project_name: str) -> bytes:
    """Generate a professional market analysis PDF using fpdf2."""
    from fpdf import FPDF

    s = _sanitize_latin1

    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=20)

    # --- Title Page ---
    pdf.add_page()
    pdf.ln(50)
    pdf.set_font("Helvetica", "B", 28)
    pdf.cell(0, 15, s(project_name), new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.ln(5)
    pdf.set_font("Helvetica", "", 18)
    pdf.cell(0, 12, "Market Analysis Report", new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.ln(10)
    pdf.set_font("Helvetica", "", 11)
    pdf.cell(0, 8, f"Generated: {datetime.now(timezone.utc).strftime('%B %d, %Y')}", new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.ln(60)
    pdf.set_font("Helvetica", "I", 9)
    pdf.cell(0, 8, "Generated by Ide/AI", new_x="LMARGIN", new_y="NEXT", align="C")

    # Helper: section header
    def section_header(title: str):
        pdf.add_page()
        pdf.set_font("Helvetica", "B", 18)
        pdf.cell(0, 12, s(title), new_x="LMARGIN", new_y="NEXT")
        pdf.ln(3)
        # Divider line
        pdf.set_draw_color(0, 229, 255)
        pdf.set_line_width(0.5)
        pdf.line(10, pdf.get_y(), 200, pdf.get_y())
        pdf.ln(6)

    def sub_header(title: str):
        pdf.set_font("Helvetica", "B", 13)
        pdf.cell(0, 10, s(title), new_x="LMARGIN", new_y="NEXT")
        pdf.ln(2)

    def body_text(text: str):
        pdf.set_font("Helvetica", "", 10)
        pdf.multi_cell(0, 5.5, s(text))
        pdf.ln(3)

    def bullet(text: str):
        pdf.set_font("Helvetica", "", 10)
        pdf.cell(5)
        pdf.multi_cell(0, 5.5, s(f"  * {text}"))

    # --- Executive Summary ---
    section_header("Executive Summary")
    summaries = []
    if analysis.target_market and isinstance(analysis.target_market, dict):
        summaries.append(analysis.target_market.get("summary", ""))
    if analysis.competitive_landscape and isinstance(analysis.competitive_landscape, dict):
        summaries.append(analysis.competitive_landscape.get("summary", ""))
    if analysis.marketing_strategies and isinstance(analysis.marketing_strategies, dict):
        summaries.append(analysis.marketing_strategies.get("summary", ""))
    body_text(" ".join(filter(None, summaries)) or "No executive summary data available.")

    # Key metrics snapshot
    if analysis.market_metrics and isinstance(analysis.market_metrics, dict):
        metrics = analysis.market_metrics
        sub_header("Key Market Metrics")
        pdf.set_font("Helvetica", "B", 11)
        tam_val = _fmt_usd(metrics.get("tam", {}).get("value_usd", 0))
        sam_val = _fmt_usd(metrics.get("sam", {}).get("value_usd", 0))
        som_val = _fmt_usd(metrics.get("som", {}).get("value_usd", 0))
        pdf.cell(60, 8, s(f"TAM: {tam_val}"), border=1, align="C")
        pdf.cell(60, 8, s(f"SAM: {sam_val}"), border=1, align="C")
        pdf.cell(60, 8, s(f"SOM: {som_val}"), border=1, new_x="LMARGIN", new_y="NEXT", align="C")
        pdf.ln(3)
        growth = metrics.get("growth_rate_pct", "N/A")
        maturity = _safe(metrics.get("market_maturity"))
        pdf.set_font("Helvetica", "", 10)
        pdf.cell(0, 6, s(f"Growth Rate: {growth}%  |  Market Maturity: {maturity}"), new_x="LMARGIN", new_y="NEXT")
        pdf.ln(5)

    # --- Target Market ---
    if analysis.target_market and isinstance(analysis.target_market, dict):
        tm = analysis.target_market
        section_header("Target Market Assessment")
        body_text(_safe(tm.get("summary")))

        # Demographics table
        demographics = tm.get("demographics", {})
        if demographics:
            sub_header("Demographics")
            pdf.set_font("Helvetica", "B", 10)
            pdf.cell(60, 7, "Attribute", border=1)
            pdf.cell(0, 7, "Value", border=1, new_x="LMARGIN", new_y="NEXT")
            pdf.set_font("Helvetica", "", 10)
            for key, val in demographics.items():
                label = key.replace("_", " ").title()
                pdf.cell(60, 7, s(label), border=1)
                pdf.cell(0, 7, s(str(val)), border=1, new_x="LMARGIN", new_y="NEXT")
            pdf.ln(5)

        # Market segments
        segments = tm.get("market_segments", [])
        if segments:
            sub_header("Market Segments")
            pdf.set_font("Helvetica", "B", 10)
            pdf.cell(50, 7, "Segment", border=1)
            pdf.cell(25, 7, "Size %", border=1, align="C")
            pdf.cell(25, 7, "Priority", border=1, align="C")
            pdf.cell(0, 7, "Description", border=1, new_x="LMARGIN", new_y="NEXT")
            pdf.set_font("Helvetica", "", 9)
            for seg in segments:
                pdf.cell(50, 7, s(seg.get("name", "")), border=1)
                pdf.cell(25, 7, s(f"{seg.get('size_pct', 0)}%"), border=1, align="C")
                pdf.cell(25, 7, s(seg.get("priority", "")), border=1, align="C")
                desc = seg.get("description", "")[:60]
                pdf.cell(0, 7, s(desc), border=1, new_x="LMARGIN", new_y="NEXT")
            pdf.ln(5)

        # User personas
        personas = tm.get("user_personas", [])
        if personas:
            sub_header("User Personas")
            for persona in personas:
                pdf.set_font("Helvetica", "B", 10)
                pdf.cell(0, 7, s(f"{persona.get('name', 'Unnamed')} -- {persona.get('role', '')}"), new_x="LMARGIN", new_y="NEXT")
                pdf.set_font("Helvetica", "", 10)
                pdf.cell(0, 6, s(f"  Goal: {persona.get('goal', 'N/A')}"), new_x="LMARGIN", new_y="NEXT")
                pdf.cell(0, 6, s(f"  Frustration: {persona.get('frustration', 'N/A')}"), new_x="LMARGIN", new_y="NEXT")
                pdf.ln(2)

    # --- Competitive Landscape ---
    if analysis.competitive_landscape and isinstance(analysis.competitive_landscape, dict):
        cl = analysis.competitive_landscape
        section_header("Competitive Landscape")
        body_text(_safe(cl.get("summary")))

        # Competitors table
        direct = cl.get("direct_competitors", [])
        if direct:
            sub_header("Direct Competitors")
            pdf.set_font("Helvetica", "B", 9)
            pdf.cell(35, 7, "Competitor", border=1)
            pdf.cell(20, 7, "Share", border=1, align="C")
            pdf.cell(20, 7, "Threat", border=1, align="C")
            pdf.cell(45, 7, "Strengths", border=1)
            pdf.cell(0, 7, "Weaknesses", border=1, new_x="LMARGIN", new_y="NEXT")
            pdf.set_font("Helvetica", "", 8)
            for comp in direct:
                name = comp.get("name", "")[:18]
                share = f"{comp.get('market_share_pct', 'N/A')}%"
                threat = comp.get("threat_level", "N/A")
                strengths = ", ".join(comp.get("strengths", []))[:40]
                weaknesses = ", ".join(comp.get("weaknesses", []))[:40]
                pdf.cell(35, 7, s(name), border=1)
                pdf.cell(20, 7, s(share), border=1, align="C")
                pdf.cell(20, 7, s(threat), border=1, align="C")
                pdf.cell(45, 7, s(strengths), border=1)
                pdf.cell(0, 7, s(weaknesses), border=1, new_x="LMARGIN", new_y="NEXT")
            pdf.ln(5)

        # Competitive advantages
        advantages = cl.get("competitive_advantages", [])
        if advantages:
            sub_header("Your Competitive Advantages")
            for adv in advantages:
                bullet(adv)
            pdf.ln(3)

        # Market gaps
        gaps = cl.get("market_gaps", [])
        if gaps:
            sub_header("Market Gaps & Opportunities")
            for gap in gaps:
                bullet(gap)
            pdf.ln(3)

    # --- Market Metrics ---
    if analysis.market_metrics and isinstance(analysis.market_metrics, dict):
        metrics = analysis.market_metrics
        section_header("Market Metrics & TAM/SAM/SOM")

        # TAM/SAM/SOM detailed
        for key_name, label in [("tam", "TAM (Total Addressable Market)"), ("sam", "SAM (Serviceable Addressable Market)"), ("som", "SOM (Serviceable Obtainable Market)")]:
            metric = metrics.get(key_name, {})
            if metric:
                sub_header(label)
                pdf.set_font("Helvetica", "B", 14)
                pdf.cell(0, 10, s(_fmt_usd(metric.get("value_usd", 0))), new_x="LMARGIN", new_y="NEXT")
                pdf.set_font("Helvetica", "", 10)
                body_text(_safe(metric.get("description")))
                if metric.get("methodology"):
                    pdf.set_font("Helvetica", "I", 9)
                    pdf.multi_cell(0, 5, s(f"Methodology: {metric['methodology']}"))
                    pdf.ln(3)

        # Industry trends
        trends = metrics.get("industry_trends", [])
        if trends:
            sub_header("Industry Trends")
            for trend in trends:
                direction = trend.get("direction", "neutral")
                indicator = "+" if direction == "positive" else "-" if direction == "negative" else "~"
                bullet(f"[{indicator}] {trend.get('trend', '')} -- {trend.get('impact', '')}")
            pdf.ln(3)

    # --- Revenue Projections ---
    if analysis.revenue_projections and isinstance(analysis.revenue_projections, dict):
        rev = analysis.revenue_projections
        section_header("Revenue Projections")

        # Pricing model
        pdf.set_font("Helvetica", "B", 11)
        pdf.cell(0, 8, s(f"Recommended Model: {_safe(rev.get('pricing_model'))}"), new_x="LMARGIN", new_y="NEXT")
        if rev.get("break_even_months"):
            pdf.set_font("Helvetica", "", 10)
            pdf.cell(0, 6, s(f"Estimated Break-Even: {rev['break_even_months']} months"), new_x="LMARGIN", new_y="NEXT")
        pdf.ln(5)

        # Pricing tiers table
        tiers = rev.get("pricing_tiers", [])
        if tiers:
            sub_header("Pricing Tiers")
            pdf.set_font("Helvetica", "B", 9)
            pdf.cell(35, 7, "Tier", border=1)
            pdf.cell(25, 7, "Price/mo", border=1, align="C")
            pdf.cell(40, 7, "Target Segment", border=1)
            pdf.cell(0, 7, "Key Features", border=1, new_x="LMARGIN", new_y="NEXT")
            pdf.set_font("Helvetica", "", 9)
            for tier in tiers:
                price = "Free" if tier.get("price_monthly", 0) == 0 else f"${tier.get('price_monthly', 0)}/mo"
                features = ", ".join(tier.get("features", []))[:50]
                pdf.cell(35, 7, s(tier.get("name", "")), border=1)
                pdf.cell(25, 7, s(price), border=1, align="C")
                pdf.cell(40, 7, s(tier.get("target_segment", "")[:25]), border=1)
                pdf.cell(0, 7, s(features), border=1, new_x="LMARGIN", new_y="NEXT")
            pdf.ln(5)

        # 3-Year projections table
        scenarios = rev.get("scenarios", {})
        if scenarios:
            sub_header("3-Year Revenue Scenarios")
            pdf.set_font("Helvetica", "B", 9)
            pdf.cell(25, 7, "Scenario", border=1)
            pdf.cell(25, 7, "Year 1", border=1, align="C")
            pdf.cell(25, 7, "Year 2", border=1, align="C")
            pdf.cell(25, 7, "Year 3", border=1, align="C")
            pdf.cell(25, 7, "Yr1 MRR", border=1, align="C")
            pdf.cell(25, 7, "Yr3 Users", border=1, align="C")
            pdf.cell(0, 7, "Yr3 Paying", border=1, new_x="LMARGIN", new_y="NEXT", align="C")
            pdf.set_font("Helvetica", "", 9)
            for scenario_key, label in [("best_case", "Best"), ("likely_case", "Likely"), ("worst_case", "Worst")]:
                sc = scenarios.get(scenario_key, {})
                y1 = sc.get("year_1", {})
                y2 = sc.get("year_2", {})
                y3 = sc.get("year_3", {})
                pdf.cell(25, 7, s(label), border=1)
                pdf.cell(25, 7, s(_fmt_usd(y1.get("revenue", 0))), border=1, align="C")
                pdf.cell(25, 7, s(_fmt_usd(y2.get("revenue", 0))), border=1, align="C")
                pdf.cell(25, 7, s(_fmt_usd(y3.get("revenue", 0))), border=1, align="C")
                pdf.cell(25, 7, s(_fmt_usd(y1.get("mrr", 0))), border=1, align="C")
                pdf.cell(25, 7, s(_fmt_number(y3.get("users", 0))), border=1, align="C")
                pdf.cell(0, 7, s(_fmt_number(y3.get("paying_users", 0))), border=1, new_x="LMARGIN", new_y="NEXT", align="C")
            pdf.ln(5)

    # --- Marketing Strategy ---
    if analysis.marketing_strategies and isinstance(analysis.marketing_strategies, dict):
        ms = analysis.marketing_strategies
        section_header("Marketing Strategy")
        body_text(_safe(ms.get("summary")))

        # Budget summary
        budget = ms.get("budget_summary", {})
        if budget:
            sub_header("Budget Overview")
            pdf.set_font("Helvetica", "", 10)
            monthly_min = _fmt_usd(budget.get("monthly_min_usd", 0))
            monthly_max = _fmt_usd(budget.get("monthly_max_usd", 0))
            pdf.cell(0, 7, s(f"Monthly Range: {monthly_min} -- {monthly_max}"), new_x="LMARGIN", new_y="NEXT")
            allocation = budget.get("allocation", [])
            if allocation:
                for alloc in allocation:
                    bullet(f"{alloc.get('category', '')}: {alloc.get('pct', 0)}%")
            pdf.ln(3)

        # Channels
        channels = ms.get("channels", [])
        if channels:
            sub_header("Marketing Channels")
            pdf.set_font("Helvetica", "B", 9)
            pdf.cell(35, 7, "Channel", border=1)
            pdf.cell(20, 7, "Priority", border=1, align="C")
            pdf.cell(25, 7, "Budget/mo", border=1, align="C")
            pdf.cell(20, 7, "CAC", border=1, align="C")
            pdf.cell(0, 7, "Key Tactics", border=1, new_x="LMARGIN", new_y="NEXT")
            pdf.set_font("Helvetica", "", 8)
            for ch in channels:
                tactics = ", ".join(ch.get("tactics", []))[:50]
                pdf.cell(35, 7, s(ch.get("name", "")[:20]), border=1)
                pdf.cell(20, 7, s(ch.get("priority", "")), border=1, align="C")
                pdf.cell(25, 7, s(_fmt_usd(ch.get("budget_monthly_usd", 0))), border=1, align="C")
                pdf.cell(20, 7, s(f"${ch.get('expected_cac', 0)}"), border=1, align="C")
                pdf.cell(0, 7, s(tactics), border=1, new_x="LMARGIN", new_y="NEXT")
            pdf.ln(5)

        # Launch strategy
        launch = ms.get("launch_strategy", {})
        if launch:
            sub_header("Launch Playbook")
            for phase, label in [("pre_launch", "Pre-Launch"), ("launch_week", "Launch Week"), ("post_launch", "Post-Launch (30-90 days)")]:
                items = launch.get(phase, [])
                if items:
                    pdf.set_font("Helvetica", "B", 10)
                    pdf.cell(0, 7, s(label), new_x="LMARGIN", new_y="NEXT")
                    for item in items:
                        bullet(item)
                    pdf.ln(2)

    # --- Footer on every page ---
    for page_num in range(1, pdf.page + 1):
        pdf.page = page_num
        pdf.set_y(-15)
        pdf.set_font("Helvetica", "I", 8)
        pdf.cell(0, 8, s(f"Generated by Ide/AI  |  {project_name}  |  Page {page_num}"), align="C")

    return pdf.output()


# ---------------------------------------------------------------------------
# DOCX generation
# ---------------------------------------------------------------------------

def generate_docx(analysis: MarketAnalysis, project_name: str) -> bytes:
    """Generate a Word document market analysis report using python-docx."""
    from docx import Document
    from docx.shared import Inches, Pt
    from docx.enum.text import WD_ALIGN_PARAGRAPH

    doc = Document()

    # Title
    title = doc.add_heading(project_name, level=0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    subtitle = doc.add_paragraph("Market Analysis Report")
    subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
    subtitle.style = doc.styles["Subtitle"]

    date_p = doc.add_paragraph(f"Generated: {datetime.now(timezone.utc).strftime('%B %d, %Y')}")
    date_p.alignment = WD_ALIGN_PARAGRAPH.CENTER

    doc.add_page_break()

    # --- Executive Summary ---
    doc.add_heading("Executive Summary", level=1)
    summaries = []
    if analysis.target_market and isinstance(analysis.target_market, dict):
        summaries.append(analysis.target_market.get("summary", ""))
    if analysis.competitive_landscape and isinstance(analysis.competitive_landscape, dict):
        summaries.append(analysis.competitive_landscape.get("summary", ""))
    if analysis.marketing_strategies and isinstance(analysis.marketing_strategies, dict):
        summaries.append(analysis.marketing_strategies.get("summary", ""))
    doc.add_paragraph(" ".join(filter(None, summaries)) or "No executive summary data available.")

    # Key metrics
    if analysis.market_metrics and isinstance(analysis.market_metrics, dict):
        metrics = analysis.market_metrics
        doc.add_heading("Key Market Metrics", level=2)
        table = doc.add_table(rows=1, cols=3)
        table.style = "Light Grid Accent 1"
        for i, (label, key) in enumerate([("TAM", "tam"), ("SAM", "sam"), ("SOM", "som")]):
            cell = table.rows[0].cells[i]
            val = _fmt_usd(metrics.get(key, {}).get("value_usd", 0))
            cell.text = f"{label}: {val}"

    # --- Target Market ---
    if analysis.target_market and isinstance(analysis.target_market, dict):
        tm = analysis.target_market
        doc.add_heading("Target Market Assessment", level=1)
        doc.add_paragraph(_safe(tm.get("summary")))

        # Demographics
        demographics = tm.get("demographics", {})
        if demographics:
            doc.add_heading("Demographics", level=2)
            table = doc.add_table(rows=len(demographics) + 1, cols=2)
            table.style = "Light Grid Accent 1"
            table.rows[0].cells[0].text = "Attribute"
            table.rows[0].cells[1].text = "Value"
            for i, (key, val) in enumerate(demographics.items(), 1):
                table.rows[i].cells[0].text = key.replace("_", " ").title()
                table.rows[i].cells[1].text = str(val)

        # Market segments
        segments = tm.get("market_segments", [])
        if segments:
            doc.add_heading("Market Segments", level=2)
            table = doc.add_table(rows=len(segments) + 1, cols=4)
            table.style = "Light Grid Accent 1"
            for i, h in enumerate(["Segment", "Size %", "Priority", "Description"]):
                table.rows[0].cells[i].text = h
            for i, seg in enumerate(segments, 1):
                table.rows[i].cells[0].text = seg.get("name", "")
                table.rows[i].cells[1].text = f"{seg.get('size_pct', 0)}%"
                table.rows[i].cells[2].text = seg.get("priority", "")
                table.rows[i].cells[3].text = seg.get("description", "")

        # User personas
        personas = tm.get("user_personas", [])
        if personas:
            doc.add_heading("User Personas", level=2)
            for persona in personas:
                p = doc.add_paragraph(style="List Bullet")
                run = p.add_run(f"{persona.get('name', 'Unnamed')} ({persona.get('role', '')})")
                run.bold = True
                p.add_run(f"\nGoal: {persona.get('goal', 'N/A')}")
                p.add_run(f"\nFrustration: {persona.get('frustration', 'N/A')}")

    # --- Competitive Landscape ---
    if analysis.competitive_landscape and isinstance(analysis.competitive_landscape, dict):
        cl = analysis.competitive_landscape
        doc.add_heading("Competitive Landscape", level=1)
        doc.add_paragraph(_safe(cl.get("summary")))

        direct = cl.get("direct_competitors", [])
        if direct:
            doc.add_heading("Direct Competitors", level=2)
            table = doc.add_table(rows=len(direct) + 1, cols=5)
            table.style = "Light Grid Accent 1"
            for i, h in enumerate(["Competitor", "Market Share", "Threat Level", "Strengths", "Weaknesses"]):
                table.rows[0].cells[i].text = h
            for i, comp in enumerate(direct, 1):
                table.rows[i].cells[0].text = comp.get("name", "")
                table.rows[i].cells[1].text = f"{comp.get('market_share_pct', 'N/A')}%"
                table.rows[i].cells[2].text = comp.get("threat_level", "")
                table.rows[i].cells[3].text = ", ".join(comp.get("strengths", []))
                table.rows[i].cells[4].text = ", ".join(comp.get("weaknesses", []))

        advantages = cl.get("competitive_advantages", [])
        if advantages:
            doc.add_heading("Your Competitive Advantages", level=2)
            for adv in advantages:
                doc.add_paragraph(adv, style="List Bullet")

        gaps = cl.get("market_gaps", [])
        if gaps:
            doc.add_heading("Market Gaps & Opportunities", level=2)
            for gap in gaps:
                doc.add_paragraph(gap, style="List Bullet")

    # --- Market Metrics ---
    if analysis.market_metrics and isinstance(analysis.market_metrics, dict):
        metrics = analysis.market_metrics
        doc.add_heading("Market Metrics & TAM/SAM/SOM", level=1)

        for key_name, label in [("tam", "TAM (Total Addressable Market)"), ("sam", "SAM (Serviceable Addressable Market)"), ("som", "SOM (Serviceable Obtainable Market)")]:
            metric = metrics.get(key_name, {})
            if metric:
                doc.add_heading(label, level=2)
                p = doc.add_paragraph()
                run = p.add_run(_fmt_usd(metric.get("value_usd", 0)))
                run.bold = True
                run.font.size = Pt(14)
                doc.add_paragraph(_safe(metric.get("description")))
                if metric.get("methodology"):
                    p = doc.add_paragraph()
                    run = p.add_run(f"Methodology: {metric['methodology']}")
                    run.italic = True

        trends = metrics.get("industry_trends", [])
        if trends:
            doc.add_heading("Industry Trends", level=2)
            for trend in trends:
                direction = trend.get("direction", "neutral")
                indicator = "[+]" if direction == "positive" else "[-]" if direction == "negative" else "[~]"
                doc.add_paragraph(f"{indicator} {trend.get('trend', '')} -- {trend.get('impact', '')}", style="List Bullet")

    # --- Revenue Projections ---
    if analysis.revenue_projections and isinstance(analysis.revenue_projections, dict):
        rev = analysis.revenue_projections
        doc.add_heading("Revenue Projections", level=1)

        p = doc.add_paragraph()
        run = p.add_run(f"Recommended Pricing Model: {_safe(rev.get('pricing_model'))}")
        run.bold = True
        if rev.get("break_even_months"):
            doc.add_paragraph(f"Estimated Break-Even: {rev['break_even_months']} months")

        # Pricing tiers
        tiers = rev.get("pricing_tiers", [])
        if tiers:
            doc.add_heading("Pricing Tiers", level=2)
            table = doc.add_table(rows=len(tiers) + 1, cols=4)
            table.style = "Light Grid Accent 1"
            for i, h in enumerate(["Tier", "Price/mo", "Target Segment", "Features"]):
                table.rows[0].cells[i].text = h
            for i, tier in enumerate(tiers, 1):
                price = "Free" if tier.get("price_monthly", 0) == 0 else f"${tier.get('price_monthly', 0)}/mo"
                table.rows[i].cells[0].text = tier.get("name", "")
                table.rows[i].cells[1].text = price
                table.rows[i].cells[2].text = tier.get("target_segment", "")
                table.rows[i].cells[3].text = ", ".join(tier.get("features", []))

        # Scenarios
        scenarios = rev.get("scenarios", {})
        if scenarios:
            doc.add_heading("3-Year Revenue Scenarios", level=2)
            table = doc.add_table(rows=4, cols=7)
            table.style = "Light Grid Accent 1"
            headers = ["Scenario", "Year 1", "Year 2", "Year 3", "Yr1 MRR", "Yr3 Users", "Yr3 Paying"]
            for i, h in enumerate(headers):
                table.rows[0].cells[i].text = h
            for row_idx, (scenario_key, label) in enumerate([("best_case", "Best"), ("likely_case", "Likely"), ("worst_case", "Worst")], 1):
                sc = scenarios.get(scenario_key, {})
                y1 = sc.get("year_1", {})
                y2 = sc.get("year_2", {})
                y3 = sc.get("year_3", {})
                table.rows[row_idx].cells[0].text = label
                table.rows[row_idx].cells[1].text = _fmt_usd(y1.get("revenue", 0))
                table.rows[row_idx].cells[2].text = _fmt_usd(y2.get("revenue", 0))
                table.rows[row_idx].cells[3].text = _fmt_usd(y3.get("revenue", 0))
                table.rows[row_idx].cells[4].text = _fmt_usd(y1.get("mrr", 0))
                table.rows[row_idx].cells[5].text = _fmt_number(y3.get("users", 0))
                table.rows[row_idx].cells[6].text = _fmt_number(y3.get("paying_users", 0))

    # --- Marketing Strategy ---
    if analysis.marketing_strategies and isinstance(analysis.marketing_strategies, dict):
        ms = analysis.marketing_strategies
        doc.add_heading("Marketing Strategy", level=1)
        doc.add_paragraph(_safe(ms.get("summary")))

        budget = ms.get("budget_summary", {})
        if budget:
            doc.add_heading("Budget Overview", level=2)
            monthly_min = _fmt_usd(budget.get("monthly_min_usd", 0))
            monthly_max = _fmt_usd(budget.get("monthly_max_usd", 0))
            doc.add_paragraph(f"Monthly Range: {monthly_min} -- {monthly_max}")
            allocation = budget.get("allocation", [])
            for alloc in allocation:
                doc.add_paragraph(f"{alloc.get('category', '')}: {alloc.get('pct', 0)}%", style="List Bullet")

        channels = ms.get("channels", [])
        if channels:
            doc.add_heading("Marketing Channels", level=2)
            table = doc.add_table(rows=len(channels) + 1, cols=5)
            table.style = "Light Grid Accent 1"
            for i, h in enumerate(["Channel", "Priority", "Budget/mo", "CAC", "Tactics"]):
                table.rows[0].cells[i].text = h
            for i, ch in enumerate(channels, 1):
                table.rows[i].cells[0].text = ch.get("name", "")
                table.rows[i].cells[1].text = ch.get("priority", "")
                table.rows[i].cells[2].text = _fmt_usd(ch.get("budget_monthly_usd", 0))
                table.rows[i].cells[3].text = f"${ch.get('expected_cac', 0)}"
                table.rows[i].cells[4].text = ", ".join(ch.get("tactics", []))

        launch = ms.get("launch_strategy", {})
        if launch:
            doc.add_heading("Launch Playbook", level=2)
            for phase, label in [("pre_launch", "Pre-Launch"), ("launch_week", "Launch Week"), ("post_launch", "Post-Launch (30-90 days)")]:
                items = launch.get(phase, [])
                if items:
                    doc.add_heading(label, level=3)
                    for item in items:
                        doc.add_paragraph(item, style="List Bullet")

    # Footer
    footer = doc.add_paragraph()
    footer.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = footer.add_run("Generated by Ide/AI")
    run.italic = True

    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()


# ---------------------------------------------------------------------------
# Plain text generation
# ---------------------------------------------------------------------------

def generate_text(analysis: MarketAnalysis, project_name: str) -> str:
    """Generate a plain text market analysis report."""
    lines = []
    sep = "=" * 60

    lines.append(sep)
    lines.append(f"  {project_name}")
    lines.append("  Market Analysis Report")
    lines.append(f"  Generated: {datetime.now(timezone.utc).strftime('%B %d, %Y')}")
    lines.append(sep)
    lines.append("")

    # --- Executive Summary ---
    lines.append("EXECUTIVE SUMMARY")
    lines.append("-" * 40)
    summaries = []
    if analysis.target_market and isinstance(analysis.target_market, dict):
        summaries.append(analysis.target_market.get("summary", ""))
    if analysis.competitive_landscape and isinstance(analysis.competitive_landscape, dict):
        summaries.append(analysis.competitive_landscape.get("summary", ""))
    if analysis.marketing_strategies and isinstance(analysis.marketing_strategies, dict):
        summaries.append(analysis.marketing_strategies.get("summary", ""))
    lines.append(" ".join(filter(None, summaries)) or "No executive summary data available.")
    lines.append("")

    # Key metrics
    if analysis.market_metrics and isinstance(analysis.market_metrics, dict):
        metrics = analysis.market_metrics
        tam = _fmt_usd(metrics.get("tam", {}).get("value_usd", 0))
        sam = _fmt_usd(metrics.get("sam", {}).get("value_usd", 0))
        som = _fmt_usd(metrics.get("som", {}).get("value_usd", 0))
        lines.append(f"  TAM: {tam}  |  SAM: {sam}  |  SOM: {som}")
        lines.append(f"  Growth Rate: {metrics.get('growth_rate_pct', 'N/A')}%  |  Maturity: {_safe(metrics.get('market_maturity'))}")
        lines.append("")

    # --- Target Market ---
    if analysis.target_market and isinstance(analysis.target_market, dict):
        tm = analysis.target_market
        lines.append(sep)
        lines.append("TARGET MARKET ASSESSMENT")
        lines.append("-" * 40)
        lines.append(_safe(tm.get("summary")))
        lines.append("")

        demographics = tm.get("demographics", {})
        if demographics:
            lines.append("Demographics:")
            for key, val in demographics.items():
                lines.append(f"  {key.replace('_', ' ').title()}: {val}")
            lines.append("")

        segments = tm.get("market_segments", [])
        if segments:
            lines.append("Market Segments:")
            for seg in segments:
                lines.append(f"  * {seg.get('name', '')} ({seg.get('size_pct', 0)}%, {seg.get('priority', '')})")
                lines.append(f"    {seg.get('description', '')}")
            lines.append("")

        personas = tm.get("user_personas", [])
        if personas:
            lines.append("User Personas:")
            for persona in personas:
                lines.append(f"  * {persona.get('name', '')} -- {persona.get('role', '')}")
                lines.append(f"    Goal: {persona.get('goal', 'N/A')}")
                lines.append(f"    Frustration: {persona.get('frustration', 'N/A')}")
            lines.append("")

    # --- Competitive Landscape ---
    if analysis.competitive_landscape and isinstance(analysis.competitive_landscape, dict):
        cl = analysis.competitive_landscape
        lines.append(sep)
        lines.append("COMPETITIVE LANDSCAPE")
        lines.append("-" * 40)
        lines.append(_safe(cl.get("summary")))
        lines.append("")

        direct = cl.get("direct_competitors", [])
        if direct:
            lines.append("Direct Competitors:")
            for comp in direct:
                lines.append(f"  * {comp.get('name', '')} (Threat: {comp.get('threat_level', 'N/A')}, Share: {comp.get('market_share_pct', 'N/A')}%)")
                lines.append(f"    Strengths: {', '.join(comp.get('strengths', []))}")
                lines.append(f"    Weaknesses: {', '.join(comp.get('weaknesses', []))}")
                if comp.get("pricing"):
                    lines.append(f"    Pricing: {comp['pricing']}")
            lines.append("")

        advantages = cl.get("competitive_advantages", [])
        if advantages:
            lines.append("Your Competitive Advantages:")
            for adv in advantages:
                lines.append(f"  + {adv}")
            lines.append("")

        gaps = cl.get("market_gaps", [])
        if gaps:
            lines.append("Market Gaps:")
            for gap in gaps:
                lines.append(f"  * {gap}")
            lines.append("")

    # --- Revenue Projections ---
    if analysis.revenue_projections and isinstance(analysis.revenue_projections, dict):
        rev = analysis.revenue_projections
        lines.append(sep)
        lines.append("REVENUE PROJECTIONS")
        lines.append("-" * 40)
        lines.append(f"Pricing Model: {_safe(rev.get('pricing_model'))}")
        if rev.get("break_even_months"):
            lines.append(f"Break-Even: {rev['break_even_months']} months")
        lines.append("")

        tiers = rev.get("pricing_tiers", [])
        if tiers:
            lines.append("Pricing Tiers:")
            for tier in tiers:
                price = "Free" if tier.get("price_monthly", 0) == 0 else f"${tier.get('price_monthly', 0)}/mo"
                lines.append(f"  * {tier.get('name', '')} ({price}) -- {tier.get('target_segment', '')}")
            lines.append("")

        scenarios = rev.get("scenarios", {})
        if scenarios:
            lines.append("3-Year Revenue Scenarios:")
            for scenario_key, label in [("best_case", "Best Case"), ("likely_case", "Likely Case"), ("worst_case", "Worst Case")]:
                sc = scenarios.get(scenario_key, {})
                if sc:
                    lines.append(f"  {label}:")
                    for yr_key, yr_label in [("year_1", "Year 1"), ("year_2", "Year 2"), ("year_3", "Year 3")]:
                        yr = sc.get(yr_key, {})
                        lines.append(f"    {yr_label}: Revenue {_fmt_usd(yr.get('revenue', 0))}, MRR {_fmt_usd(yr.get('mrr', 0))}, Users {_fmt_number(yr.get('users', 0))}")
            lines.append("")

    # --- Marketing Strategy ---
    if analysis.marketing_strategies and isinstance(analysis.marketing_strategies, dict):
        ms = analysis.marketing_strategies
        lines.append(sep)
        lines.append("MARKETING STRATEGY")
        lines.append("-" * 40)
        lines.append(_safe(ms.get("summary")))
        lines.append("")

        budget = ms.get("budget_summary", {})
        if budget:
            lines.append(f"Monthly Budget: {_fmt_usd(budget.get('monthly_min_usd', 0))} -- {_fmt_usd(budget.get('monthly_max_usd', 0))}")
            lines.append("")

        channels = ms.get("channels", [])
        if channels:
            lines.append("Channels:")
            for ch in channels:
                lines.append(f"  * {ch.get('name', '')} ({ch.get('priority', '')}) -- Budget: {_fmt_usd(ch.get('budget_monthly_usd', 0))}/mo, CAC: ${ch.get('expected_cac', 0)}")
                tactics = ch.get("tactics", [])
                if tactics:
                    lines.append(f"    Tactics: {', '.join(tactics)}")
            lines.append("")

    lines.append(sep)
    lines.append("Generated by Ide/AI")
    lines.append(sep)

    return "\n".join(lines)
