"""
transcript_service.py — Format discovery transcripts for export.
Supports PDF, TXT, and Markdown formats.
"""
from datetime import datetime, timezone

from app.services.export_service import _sanitize_latin1


def format_as_text(messages: list[dict], project_name: str) -> str:
    """Format messages as clean readable plain text.

    Example output:
        Discovery Transcript — My Project
        Generated: 2025-01-15

        [AI] Welcome! Let's explore your idea...
        [You] I want to build a task manager...
    """
    lines = [
        f"Discovery Transcript -- {project_name}",
        f"Generated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}",
        "",
        "=" * 60,
        "",
    ]

    for msg in messages:
        role = msg.get("role", "unknown")
        content = msg.get("content", "")
        label = "[AI]" if role == "assistant" else "[You]"
        lines.append(f"{label} {content}")
        lines.append("")

    lines.append("=" * 60)
    lines.append(f"End of transcript -- {len(messages)} messages")
    lines.append("Generated by Ide/AI")

    return "\n".join(lines)


def format_as_pdf(messages: list[dict], project_name: str) -> bytes:
    """Generate a formatted PDF transcript using fpdf2.

    Includes project name as title, messages with role labels,
    and uses Latin-1 sanitization for font compatibility.
    """
    from fpdf import FPDF

    s = _sanitize_latin1

    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    # Title
    pdf.set_font("Helvetica", "B", 20)
    pdf.cell(0, 12, s(f"Discovery Transcript"), new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 12)
    pdf.cell(0, 8, s(project_name), new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "I", 9)
    pdf.cell(
        0, 6,
        s(f"Generated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}"),
        new_x="LMARGIN", new_y="NEXT",
    )
    pdf.ln(8)

    # Divider
    pdf.set_draw_color(100, 100, 100)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(6)

    # Messages
    for msg in messages:
        role = msg.get("role", "unknown")
        content = msg.get("content", "")
        label = "AI" if role == "assistant" else "You"

        # Role label
        if role == "assistant":
            pdf.set_font("Helvetica", "B", 10)
            pdf.set_text_color(0, 150, 200)
        else:
            pdf.set_font("Helvetica", "B", 10)
            pdf.set_text_color(80, 80, 80)

        pdf.cell(0, 6, s(f"[{label}]"), new_x="LMARGIN", new_y="NEXT")

        # Message content
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(30, 30, 30)
        pdf.multi_cell(0, 5, s(content))
        pdf.ln(4)

    # Footer divider
    pdf.ln(4)
    pdf.set_draw_color(100, 100, 100)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(6)

    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(120, 120, 120)
    pdf.cell(0, 5, s(f"{len(messages)} messages | Generated by Ide/AI"))

    return pdf.output()


def format_as_markdown(messages: list[dict], project_name: str) -> str:
    """Format messages as markdown with headers and blockquotes.

    Example output:
        # Discovery Transcript — My Project
        _Generated: 2025-01-15_

        ---

        **AI:**
        > Welcome! Let's explore your idea...

        **You:**
        > I want to build a task manager...
    """
    lines = [
        f"# Discovery Transcript -- {project_name}",
        f"_Generated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}_",
        "",
        "---",
        "",
    ]

    for msg in messages:
        role = msg.get("role", "unknown")
        content = msg.get("content", "")
        label = "AI" if role == "assistant" else "You"

        lines.append(f"**{label}:**")

        # Blockquote each line of the content
        for line in content.split("\n"):
            lines.append(f"> {line}")

        lines.append("")

    lines.append("---")
    lines.append(f"_{len(messages)} messages | Generated by Ide/AI_")

    return "\n".join(lines)
